alias cp='cp -R'
alias scp='scp -r'
alias grep='grep --color=auto'
alias ..='cd ..'
alias ...-'../../'
alias ....='../../..'
alias .....='../../../..'
alias ......='../../../../..'
alias mkdir='mkdir -p'
alias df='df -kTh'
alias top='gotop'
alias htop='gotop'
alias vi='nvim'
alias vim='nvim'
alias ping='ping -c 3'
alias s='sudo '
alias se='sudoedit'
alias sctl='systemctl'
alias jctl='journalctl'

